name: CI for Phonebook Filter By Age App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js LTS (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # Node 18 LTS

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      # We don't want immutable-cache, just a frozen `yarn.lock` file

      - name: Run tests
        run: |
          yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Update PR with Test Results
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-success: |
            # Tests passed! :white_check_mark:
          message-failure: |
            # Tests failed! :x:
          message-id: test-results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the `git-log.txt` file
        run: |
          echo "# Git Log" > git-log.txt
          git log --pretty="âœ… %s%n%B%n%n" main...HEAD --reverse >> git-log.txt

      - name: Update PR with Test Results
        if: ${{ github.event_name == 'pull_request' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-path: git-log.txt
          message-id: git-log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
