name: CI for Phonebook Filter By Age App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js LTS (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # Node 18 LTS

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      # We don't want immutable-cache, just a frozen `yarn.lock` file

      - name: Run tests
        run: |
          yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Update PR with Result
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          RESULT="Failed :x:"
          if success; then
            RESULT="Success :white_check_mark:"
          fi

          PR_COMMENT="Tests $RESULT"

          echo "Adding PR comment: $PR_COMMENT"

          echo $PR_COMMENT | gh pr comment ${{ github.event.pull_request.number }} --body -

      - name: Log git history
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git log --oneline | gh pr comment ${{ github.event.pull_request.number }} --body -
